# Generated by Django 6.0.6 on 2026-06-26 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='accepted_answers',
        ),
        migrations.AddField(
            model_name='question',
            name='accepted_answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for_questions', to='answers.answer'),
        ),
    ]
